version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx"
        restart: always
        ports:
            - "8080:8080"
        environment:
           - TZ=Asia/Shanghai
        depends_on:
           - "php"
        volumes:
           - "./nginx/conf.d:/etc/nginx/conf.d"
           - "./www:/usr/share/nginx/html"
           - "./nginx/log:/var/log/nginx"
        networks:
           - net-app
    php:
        build: .
        image: php7.4_fpm_image
        container_name: "compose-php"
        restart: always
        ports:
            - "9000:9000"
        user: "${UID:-1000}"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./www:/usr/share/nginx/html"
            - "./php/php.ini:/usr/local/etc/php/php.ini"
        networks:
           - net-app

networks:
    net-app: